### ISSUE TITLE
Crash on astrometry driver property missing

### ISSUE THREAD

**Issue by GuLinux** [GuLinux/AstroPhoto-Plus#109]
```
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]: Traceback (most recent call last):
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/home/stargazer/.local/share/AstroPhotoPlus/python-venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                                                                     
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     response = self.full_dispatch_request()
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/home/stargazer/.local/share/AstroPhotoPlus/python-venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                                                                        
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     rv = self.handle_user_exception(e)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/home/stargazer/.local/share/AstroPhotoPlus/python-venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                                                                        
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     reraise(exc_type, exc_value, tb)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/home/stargazer/.local/share/AstroPhotoPlus/python-venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise                                                                                                                                    
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     raise value
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/home/stargazer/.local/share/AstroPhotoPlus/python-venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request                                                                                                                        
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     rv = self.dispatch_request()
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/home/stargazer/.local/share/AstroPhotoPlus/python-venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request                                                                                                                             
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     return self.view_functions[rule.endpoint](**req.view_args)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/usr/lib/AstroPhotoPlus/backend/api_decorators.py", line 43, in f_wrapper
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     return f(*args, **kwargs)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/usr/lib/AstroPhotoPlus/backend/api_decorators.py", line 26, in f_wrapper
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     return jsonify(f(*args, **kwargs))
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/usr/lib/AstroPhotoPlus/backend/api_decorators.py", line 53, in f_wrapper
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     return f(*args, **kwargs)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/usr/lib/AstroPhotoPlus/backend/api_entrypoint.py", line 476, in astrometry_solve_field
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     return lookup_astrometry(astrometry_id).solve_field(json)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/usr/lib/AstroPhotoPlus/backend/indi/astrometry.py", line 54, in solve_field
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     self.__set_astrometry_options(options)
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:   File "/usr/lib/AstroPhotoPlus/backend/indi/astrometry.py", line 105, in __set_astrometry_options
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]:     self.device.get_property('DEBUG_LEVEL').set_values({'DBG_DEBUG': True})
Feb 11 10:30:49 AstroPhoto-Plus AstroPhoto-Plus[1135]: AttributeError: 'NoneType' object has no attribute 'set_values'
```

**Comment by GuLinux** [comment]
fixed in 414cf4c5847e560f8320aecaacb63f44c98121d1
