### ISSUE TITLE
AstroPhotoPlus don't run on raspberry

### ISSUE THREAD

**Issue by Astro-Otter-Space** [GuLinux/AstroPhoto-Plus#263]
After manual installation of AstroPhpto-plus, the backend server look like not running after run `sudo AstroPhotoPlus-ctl autosetup` 

**To Reproduce**
Installation log:
```
hamham@astroloutre:~/Téléchargements$ sudo apt-get install -y ./AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Note : sélection de « astrophotoplus » au lieu de « ./AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb »
Les NOUVEAUX paquets suivants seront installés :
  astrophotoplus
0 mis à jour, 1 nouvellement installés, 0 à enlever et 0 non mis à jour.
Après cette opération, 18,0 Mo d'espace disque supplémentaires seront utilisés.
Réception de :1 /home/hamham/Téléchargements/AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb astrophotoplus all 1.0.1-b933 [5 237 kB]
Sélection du paquet astrophotoplus précédemment désélectionné.
(Lecture de la base de données... 375338 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb ...
Dépaquetage de astrophotoplus (1.0.1-b933) ...
Paramétrage de astrophotoplus (1.0.1-b933) ...
Linking /usr/share/AstroPhotoPlus/config/debian_based/etc_AstroPhotoPlus-commands.json to /etc/AstroPhotoPlus-commands.json
W: Repository is broken: astrophotoplus:armhf (= 1.0.1-b933) has no Size information
```

Then 
```
hamham@astroloutre:~/Téléchargements$ sudo AstroPhotoPlus-ctl autosetup
Using nginx as web server
'/usr/lib/AstroPhotoPlus/frontend/webserver-conf/nginx/astrophotoplus.conf' -> '/etc/nginx/sites-available/astrophotoplus.conf'
Please enter the username for your AstroPhoto Plus backend server: hamham
Autoconfiguring hamham as default AstroPhoto Plus user.
Run 'systemctl edit AstroPhotoPlus' to change user
Waiting for backend server to be ready......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

When i display logs, here's what i have:
```
juil. 03 17:21:44 astroloutre systemd[1]: Started Astrophotography sequence server.
-- Subject: L'unité (unit) AstroPhotoPlus.service a terminé son démarrage
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- L'unité (unit) AstroPhotoPlus.service a terminé son démarrage, avec le résultat done.
juil. 03 17:21:55 astroloutre AstroPhoto-Plus[3896]: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
juil. 03 17:21:55 astroloutre AstroPhoto-Plus[3896]: Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
juil. 03 17:22:05 astroloutre AstroPhoto-Plus[3951]: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
juil. 03 17:22:06 astroloutre AstroPhoto-Plus[3951]: Collecting pyindi-client>=0.2.3
juil. 03 17:22:06 astroloutre AstroPhoto-Plus[3951]:   Using cached pyindi-client-0.2.7.tar.gz (5.5 kB)
juil. 03 17:22:10 astroloutre AstroPhoto-Plus[3951]: Requirement already satisfied: astropy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.0)
juil. 03 17:22:10 astroloutre AstroPhoto-Plus[3951]: Requirement already satisfied: flask in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.1)
juil. 03 17:22:11 astroloutre AstroPhoto-Plus[3951]: Collecting flask-sse
juil. 03 17:22:11 astroloutre AstroPhoto-Plus[3951]:   Using cached Flask_SSE-1.0.0-py2.py3-none-any.whl (5.0 kB)
juil. 03 17:22:13 astroloutre AstroPhoto-Plus[3951]: Collecting gunicorn
juil. 03 17:22:13 astroloutre AstroPhoto-Plus[3951]:   Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
juil. 03 17:22:16 astroloutre AstroPhoto-Plus[3951]: Collecting gevent
juil. 03 17:22:16 astroloutre AstroPhoto-Plus[3951]:   Using cached gevent-21.1.2.tar.gz (5.9 MB)
juil. 03 17:22:36 astroloutre AstroPhoto-Plus[3951]:   Installing build dependencies: started
juil. 03 17:23:50 astroloutre AstroPhoto-Plus[3951]:   Installing build dependencies: still running...
juil. 03 17:24:00 astroloutre AstroPhoto-Plus[3951]:   Installing build dependencies: finished with status 'done'
juil. 03 17:24:00 astroloutre AstroPhoto-Plus[3951]:   Getting requirements to build wheel: started
juil. 03 17:24:39 astroloutre AstroPhoto-Plus[3951]:   Getting requirements to build wheel: finished with status 'done'
juil. 03 17:24:39 astroloutre AstroPhoto-Plus[3951]:     Preparing wheel metadata: started
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:     Preparing wheel metadata: finished with status 'error'
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:     ERROR: Command errored out with exit status 1:
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:      command: /home/hamham/.local/share/AstroPhotoPlus/python-venv/bin/python3 /tmp/tmp9y7sg0bj prepare_metadata_for_build_wheel /tmp/tmpgel24qku
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:          cwd: /tmp/pip-install-46_3ylld/gevent
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:     Complete output (40 lines):
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:     Traceback (most recent call last):
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/tmp9y7sg0bj", line 280, in <module>
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         main()
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/tmp9y7sg0bj", line 263, in main
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         json_out['return_val'] = hook(**hook_input['kwargs'])
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/tmp9y7sg0bj", line 133, in prepare_metadata_for_build_wheel
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         return hook(metadata_directory, config_settings)
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in prepare_metadata_for_build_wheel
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         self.run_setup()
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 249, in run_setup
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         super(_BuildMetaLegacyBackend,
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in run_setup
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         exec(compile(code, __file__, 'exec'), locals())
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "setup.py", line 479, in <module>
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         run_setup(EXT_MODULES)
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "setup.py", line 345, in run_setup
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         setup(
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         return distutils.core.setup(**attrs)
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         _setup_distribution = dist = klass(attrs)
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         _Distribution.__init__(self, {
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         self.finalize_options()
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         ep.load()(self)
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
juil. 03 17:24:42 astroloutre AstroPhoto-Plus[3951]:         ep.load()(self, ep.name, value)
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/pip-build-env-p84o1bay/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:         add_cffi_module(dist, cffi_module)
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/pip-build-env-p84o1bay/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:         execfile(build_file_name, mod_vars)
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/pip-build-env-p84o1bay/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:         exec(code, glob, glob)
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:       File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:         ffi = FFI()
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:       File "/tmp/pip-build-env-p84o1bay/overlay/lib/python3.8/site-packages/cffi/api.py", line 54, in __init__
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:         raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:     Exception: Version mismatch: this is the 'cffi' package version 1.14.5, located in '/tmp/pip-build-env-p84o1bay/overlay/lib/python3.8/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-38-arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]:     ----------------------------------------
juil. 03 17:24:43 astroloutre AstroPhoto-Plus[3951]: ERROR: Command errored out with exit status 1: /home/hamham/.local/share/AstroPhotoPlus/python-venv/bin/python3 /tmp/tmp9y7sg0bj prepare_metadata_for_build_wheel /tmp/tmpgel24qku Check the logs for full command output.
juil. 03 17:24:43 astroloutre systemd[1]: AstroPhotoPlus.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit AstroPhotoPlus.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
juil. 03 17:24:43 astroloutre systemd[1]: AstroPhotoPlus.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit AstroPhotoPlus.service has entered the 'failed' state with result 'exit-code'.

```

**Server Information**
- AstroPhoto Plus Version
 - Raspberry Pi 3 Model B+
 - Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1038-raspi armv7l) 
 - Python version in use: 
 ```
hamham@astroloutre:~$ python --version 
Python 2.7.18
hamham@astroloutre:~$ python3 --version 
Python 3.8.10
 ```

Thank you for advice

**Comment by Astro-Otter-Space** [comment]
Second try, i've removed the package with synaptic and try manual installation with running https://raw.githubusercontent.com/GuLinux/AstroPhoto-Plus/master/scripts/setup/ubuntu-raspbian.sh (just comment installation of indi-server because it's already installed). And same result : 
```
// Some isntallation
Saving to: ‘AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb’

AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb                 100%[=========================================================================================================================================>]   4,99M  8,47MB/s    in 0,6s    

2021-07-03 18:54:05 (8,47 MB/s) - ‘AstroPhotoPlus-1.0.1-b933-Ubuntu_Debian.deb’ saved [5237310/5237310]

// Installation of packages...
Linking /usr/share/AstroPhotoPlus/config/debian_based/etc_AstroPhotoPlus-commands.json to /etc/AstroPhotoPlus-commands.json
Traitement des actions différées (« triggers ») pour libc-bin (2.31-0ubuntu9.2) ...
Traitement des actions différées (« triggers ») pour systemd (245.4-4ubuntu3.7) ...
Traitement des actions différées (« triggers ») pour man-db (2.9.1-1) ...
Using nginx as web server
'/usr/lib/AstroPhotoPlus/frontend/webserver-conf/nginx/astrophotoplus.conf' -> '/etc/nginx/sites-available/astrophotoplus.conf'
Autoconfiguring hamham as default AstroPhoto Plus user.
Run 'systemctl edit AstroPhotoPlus' to change user
Waiting for backend server to be ready................[some hours...].................
```
 And in logs : 
```
-- L'unité (unit) AstroPhotoPlus.service a commencé à démarrer.
juil. 03 18:59:43 astroloutre systemd[1]: Started Astrophotography sequence server.
-- Subject: L'unité (unit) AstroPhotoPlus.service a terminé son démarrage
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- L'unité (unit) AstroPhotoPlus.service a terminé son démarrage, avec le résultat done.
juil. 03 18:59:53 astroloutre AstroPhoto-Plus[7869]: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
juil. 03 18:59:54 astroloutre AstroPhoto-Plus[7869]: Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
juil. 03 19:00:04 astroloutre AstroPhoto-Plus[7921]: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
juil. 03 19:00:05 astroloutre AstroPhoto-Plus[7921]: Collecting pyindi-client>=0.2.3
juil. 03 19:00:05 astroloutre AstroPhoto-Plus[7921]:   Using cached pyindi-client-0.2.7.tar.gz (5.5 kB)
juil. 03 19:00:08 astroloutre AstroPhoto-Plus[7921]: Requirement already satisfied: astropy in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.0)
juil. 03 19:00:08 astroloutre AstroPhoto-Plus[7921]: Requirement already satisfied: flask in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.1.1)
juil. 03 19:00:09 astroloutre AstroPhoto-Plus[7921]: Collecting flask-sse
juil. 03 19:00:09 astroloutre AstroPhoto-Plus[7921]:   Using cached Flask_SSE-1.0.0-py2.py3-none-any.whl (5.0 kB)
juil. 03 19:00:10 astroloutre AstroPhoto-Plus[7921]: Collecting gunicorn
juil. 03 19:00:10 astroloutre AstroPhoto-Plus[7921]:   Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
juil. 03 19:00:14 astroloutre AstroPhoto-Plus[7921]: Collecting gevent
juil. 03 19:00:14 astroloutre AstroPhoto-Plus[7921]:   Using cached gevent-21.1.2.tar.gz (5.9 MB)
juil. 03 19:00:23 astroloutre AstroPhoto-Plus[7921]:   Installing build dependencies: started
juil. 03 19:01:26 astroloutre AstroPhoto-Plus[7921]:   Installing build dependencies: still running...
juil. 03 19:02:08 astroloutre AstroPhoto-Plus[7921]:   Installing build dependencies: finished with status 'done'
juil. 03 19:02:08 astroloutre AstroPhoto-Plus[7921]:   Getting requirements to build wheel: started
juil. 03 19:02:18 astroloutre AstroPhoto-Plus[7921]:   Getting requirements to build wheel: finished with status 'done'
juil. 03 19:02:18 astroloutre AstroPhoto-Plus[7921]:     Preparing wheel metadata: started
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:     Preparing wheel metadata: finished with status 'error'
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:     ERROR: Command errored out with exit status 1:
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:      command: /home/hamham/.local/share/AstroPhotoPlus/python-venv/bin/python3 /tmp/tmpeijv1s7d prepare_metadata_for_build_wheel /tmp/tmpfbs_b_c1
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:          cwd: /tmp/pip-install-_vd9qr26/gevent
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:     Complete output (40 lines):
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:     Traceback (most recent call last):
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/tmpeijv1s7d", line 280, in <module>
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         main()
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/tmpeijv1s7d", line 263, in main
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         json_out['return_val'] = hook(**hook_input['kwargs'])
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/tmpeijv1s7d", line 133, in prepare_metadata_for_build_wheel
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         return hook(metadata_directory, config_settings)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in prepare_metadata_for_build_wheel
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         self.run_setup()
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 249, in run_setup
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         super(_BuildMetaLegacyBackend,
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in run_setup
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         exec(compile(code, __file__, 'exec'), locals())
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "setup.py", line 479, in <module>
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         run_setup(EXT_MODULES)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "setup.py", line 345, in run_setup
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         setup(
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         return distutils.core.setup(**attrs)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         _setup_distribution = dist = klass(attrs)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         _Distribution.__init__(self, {
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         self.finalize_options()
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         ep.load()(self)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         ep.load()(self, ep.name, value)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/pip-build-env-0n568wg7/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         add_cffi_module(dist, cffi_module)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/pip-build-env-0n568wg7/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         execfile(build_file_name, mod_vars)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/pip-build-env-0n568wg7/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         exec(code, glob, glob)
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "src/gevent/libev/_corecffi_build.py", line 31, in <module>
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         ffi = FFI()
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:       File "/tmp/pip-build-env-0n568wg7/overlay/lib/python3.8/site-packages/cffi/api.py", line 54, in __init__
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:         raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:     Exception: Version mismatch: this is the 'cffi' package version 1.14.5, located in '/tmp/pip-build-env-0n568wg7/overlay/lib/python3.8/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-38-arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]:     ----------------------------------------
juil. 03 19:02:22 astroloutre AstroPhoto-Plus[7921]: ERROR: Command errored out with exit status 1: /home/hamham/.local/share/AstroPhotoPlus/python-venv/bin/python3 /tmp/tmpeijv1s7d prepare_metadata_for_build_wheel /tmp/tmpfbs_b_c1 Check the logs for full command output.
juil. 03 19:02:23 astroloutre systemd[1]: AstroPhotoPlus.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit AstroPhotoPlus.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
juil. 03 19:02:23 astroloutre systemd[1]: AstroPhotoPlus.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit AstroPhotoPlus.service has entered the 'failed' state with result 'exit-code'.

```

**Comment by Astro-Otter-Space** [comment]
I will try to fix the same version of https://pypi.org/project/cffi/#history.
the error seems to come from there
```
Exception: Version mismatch: 
this is the 'cffi' package version 1.14.5, located in '/tmp/pip-build-env-0n568wg7/overlay/lib/python3.8/site-packages/cffi/api.py'.  
When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-38-arm-linux-gnueabihf.so'.  
The two versions should be equal; check your installation.
```

**Comment by Astro-Otter-Space** [comment]
Resolved with installing package "python3-cffi"
`sudo apt install python3-cffi`
and downgrade pip package :
`pip install --upgrade cffi==1.14.0`
